export const CHECK_IN_SUBSCRIBE_TEMPLATE_ID = 'CHECK_IN_LOCATION_TEMPLATE_ID'
export const ANNIVERSARY_SUBSCRIBE_TEMPLATE_ID = 'ANNIVERSARY_REMINDER_TEMPLATE_ID'
export const ORDER_SUBSCRIBE_TEMPLATE_ID = 'ORDER_CREATED_TEMPLATE_ID'
